USER_ROLE_CUSTOMER = "customer"
USER_ROLE_BUSINESS = "business"
USER_ROLE_ADMIN = "admin"

VERIF_EMAIL_PENDING = "EMAIL_PENDING"
VERIF_IDENTITY_PENDING = "IDENTITY_PENDING"
VERIF_KYC_SUBMITTED = "KYC_SUBMITTED"

VERIF_VERIFIED = "VERIFIED"
VERIF_REJECTED = "REJECTED"
VERIF_MANUAL_REVIEW = "MANUAL_REVIEW"

REQ_SUBMITTED = "SUBMITTED"
REQ_CONFIRMED = "CONFIRMED"
REQ_REJECTED = "REJECTED"
REQ_NEEDS_MORE_INFO = "NEEDS_MORE_INFO"
REQ_ERROR = "ERROR"

CERT_CERTIFIED = "CERTIFIED"

ORDER_PLACED = "PLACED"
ORDER_MATCHED = "MATCHED"
ORDER_CANCELLED = "CANCELLED"

BID_OPEN = "OPEN"
BID_FILLED = "FILLED"

CERT_RESERVED = "RESERVED"
CERT_SOLD = "SOLD"

TRADE_CREATED = "CREATED"


